export const siteCreateJson=[
    {
      "ParameterProvider": "cloudware",
      "ParameterParent": "site",
      "ParameterSerial": "1",
      "ParameterName": "siteName",
      "ParameterDataType": "Text",
      "ParameterInputType": "Textbox",
      "ParameterMandatory": "Yes",
      "ParameterLabel": "Site Name",
      "ParameterLength": "20",
      "ParameterValidation": "",
      "ParameterSource": "",
      "ParameterInfo1": "A sitename must be universally unique in the UCS universe. There are some recommendations to make your Site name unique",
      "ParameterInfo2": "Use lower case characters and hypheans, be sure to have some numenclature.",
      "ParameterInfo3": "Example: banking-app-site"
    },
    {
      "ParameterProvider": "cloudware",
      "ParameterParent": "site",
      "ParameterSerial": "2",
      "ParameterName": "siteProvider",
      "ParameterDataType": "Text",
      "ParameterInputType": "ListBox",
      "ParameterMandatory": "Yes",
      "ParameterLabel": "Site Provider",
      "ParameterLength": "20",
      "ParameterValidation": "",
      "ParameterSource": "",
      "ParameterInfo1": "A site provider can be any of the following supported Cloud service providers (CSPs):",
      "ParameterInfo2": "AWS - Amazon Web Services, HCS - HUAWEI Cloud Services, GCP - Google Cloud Services and Microsoft Azure",
      "ParameterInfo3": ""
    },
    {
      "ParameterProvider": "cloudware",
      "ParameterParent": "site",
      "ParameterSerial": "3",
      "ParameterName": "siteDescription",
      "ParameterDataType": "Text",
      "ParameterInputType": "CommentBox",
      "ParameterMandatory": "Yes",
      "ParameterLabel": "Site Description",
      "ParameterLength": "200",
      "ParameterValidation": "",
      "ParameterSource": "",
      "ParameterInfo1": "Provide some description of the site.",
      "ParameterInfo2": "Typically, you may want to describe the applications that will be hosted in the site or provide the contexts for the site.",
      "ParameterInfo3": ""
    },
    {
      "ParameterProvider": "cloudware",
      "ParameterParent": "site",
      "ParameterSerial": "4",
      "ParameterName": "siteCode",
      "ParameterDataType": "Text",
      "ParameterInputType": "Textbox",
      "ParameterMandatory": "Yes",
      "ParameterLabel": "Site Code",
      "ParameterLength": "20",
      "ParameterValidation": "",
      "ParameterSource": "",
      "ParameterInfo1": "A simple unique code that you can remember.",
      "ParameterInfo2": "The code appears on most screeens, so please choose a code that is self-descrptive and can be remembered easily.",
      "ParameterInfo3": ""
    },
    {
      "ParameterProvider": "cloudware",
      "ParameterParent": "site",
      "ParameterSerial": "5",
      "ParameterName": "siteEndDate",
      "ParameterDataType": "Date",
      "ParameterInputType": "DateBox",
      "ParameterMandatory": "Yes",
      "ParameterLabel": "Site Expiry Date",
      "ParameterLength": "20",
      "ParameterValidation": "",
      "ParameterSource": "",
      "ParameterInfo1": "What date will this site expire?",
      "ParameterInfo2": "If it will never expire, you may put a very far date.",
      "ParameterInfo3": ""
    },
    {
      "ParameterProvider": "cloudware",
      "ParameterParent": "site",
      "ParameterSerial": "6",
      "ParameterName": "siteEndOfLifeAction",
      "ParameterDataType": "Text",
      "ParameterInputType": "ListBox",
      "ParameterMandatory": "Yes",
      "ParameterLabel": "EOL Action",
      "ParameterLength": "20",
      "ParameterValidation": "",
      "ParameterSource": "ProviderList",
      "ParameterInfo1": "What action should be taken when this site reaches end of life on the End Date you specified?",
      "ParameterInfo2": "",
      "ParameterInfo3": ""
    }
  ]