export const resourceData = [
    {
      id: 1,
      label: "CPU Type",
      webServer: "4 cores",
      apiServer: "6 cores",
      dbServer: "8 cores",
    },
    {
      id: 2,
      label: "CPU Size",
      webServer: "220 SSD",
      apiServer: "220 SSD",
      dbServer: "220 SSD",
    },
    {
      id: 3,
      label: "Memory",
      webServer: "16 GB",
      apiServer: "32 GB",
      dbServer: "64 GB",
    },
    {
      id: 4,
      label: "Storage Type",
      webServer: "SSD",
      apiServer: "SSD",
      dbServer: "NVMe",
    },
    {
      id: 5,
      label: "Storage Size",
      webServer: "100 GB",
      apiServer: "500 GB",
      dbServer: "1 TB",
    },
    {
      id: 6,
      label: "Operating System",
      webServer: "Ubuntu 20.04",
      apiServer: "Ubuntu 22.04",
      dbServer: "Amazon Linux 2",
    },
    {
      id: 7,
      label: "Region",
      webServer: "us-east-1",
      apiServer: "us-west-2",
      dbServer: "eu-central-1",
    },
    {
      id: 8,
      label: "Availability Zone",
      webServer: "us-east-1a",
      apiServer: "us-west-2b",
      dbServer: "eu-central-1c",
    },
    {
      id: 9,
      label: "VPC ID",
      webServer: "vpc-001",
      apiServer: "vpc-002",
      dbServer: "vpc-003",
    },
    {
      id: 10,
      label: "Instance Type",
      webServer: "t3.micro",
      apiServer: "t3.medium",
      dbServer: "t3.large",
    },
  ];