import type { resourceType } from "./type";

export const resourceData: resourceType[] = [
  {
    resourceId: "1001",
    resourceName: "Rubies Production Site",
    houseCode: "PROD-HSE-1",
    roomCode: "db-subnet",
    provider: "AWS",
    siteCode: "RUB-PROD-SITE-1",
    resourceCode: "db-subnet",
    type: "Database",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    resourceId: "1002",
    resourceName: "Rubies Production Site",

    provider: "Huawei",
    type: "Server",
    houseCode: "PROD-HSE-2",
    roomCode: "db-subnet",
    siteCode: "RUB-PROD-SITE-1",
    resourceCode: "webapp-subnet",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    resourceId: "1003",
    resourceName: "Qoovest",
    houseCode: "PROD-HSE-1",
    siteCode: "RUB-PROD-SITE-1",
    roomCode: "appserver-subnet",
    resourceCode: "appserver-subnet",
    type: "Server",
    provider: "Huawei",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    resourceId: "1004",
    resourceName: "Qoonity",
    provider: "Huawei",
    siteCode: "RUB-PROD-SITE-1",
    resourceCode: "lb-subnet",
    roomCode: "db-subnet",

    houseCode: "PROD-HSE-1",
    type: "Database",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    resourceId: "1005",
    provider: "AWS",
    siteCode: "RUB-PROD-SITE-1",
    resourceCode: "vpn-subnet",
    resourceName: "NCube",
    roomCode: "db-subnet",
    houseCode: "PROD-HSE-1",
    type: "Database",
    createdAt: "2025-01-09",

    ipRange: "10.10.4.3",
  },
  {
    resourceId: "1006",
    resourceName: "Tymer",
    provider: "AWS",
    siteCode: "RUB-PROD-SITE-1",
    roomCode: "db-subnet",
    resourceCode: "db-subnet",
    houseCode: "PROD-HSE-1",
    type: "Database",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
];
