export enum ModalEnum {
    ADD_CUSTOM_ROLE = "ADD_CUSTOM_ROLE",
    ADD_IP_WHITELIST = "ADD_IP_WHITELIST",
    INVITE_ORG_TEAM_MEMBER = "INVITE_ORG_TEAM_MEMBER",
    MAKE_NEW_TRANSFER = "MAKE_NEW_TRANSFER",
    MAKE_NEW_BULK_TRANSFER = "MAKE_NEW_BULK_TRANSFER",
    CONTACT_US_SUPPORT_MODAL = "CONTACT_US_SUPPORT_MODAL",
    UPDATE_DUMMY_MODAL = "UPDATE_DUMMY_MODAL",
    DELETE_DUMMY_CONFIRMATION_MODAL = "DELETE_DUMMY_CONFIRMATION_MODAL",
    ViewDummyModal = "ViewDummyModal",
}
