

export const houseCreateData=[
    {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"1","ParameterName":"houseSiteCode","ParameterField":"houseSiteCode","ParameterDataType":"Text","ParameterInputType":"ListBox","ParameterMandatory":"Yes","ParameterLabel":"Site Code","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"Select from the list of sites that you have created.","ParameterInfo2":"If you do not have a site, create one first. A srever house needs a server site.","ParameterInfo3":"Basically, a server house needs to be deployed in a server site."},
    {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"2","ParameterName":"houseName","ParameterField":"houseName","ParameterDataType":"Text","ParameterInputType":"Textbox","ParameterMandatory":"Yes","ParameterLabel":"House Name","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"Provide the house name","ParameterInfo2":"","ParameterInfo3":""},
   
    // {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"2","ParameterName":"houseEndDate","ParameterField":"houseEndDate","ParameterDataType":"Date","ParameterInputType":"DateBox","ParameterMandatory":"Yes","ParameterLabel":"House Expiry Date","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"What date will this site expire?","ParameterInfo2":"If it will never expire, you may put a very far date.","ParameterInfo3":""},
    {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"3","ParameterName":"houseCode","ParameterField":"houseCode","ParameterDataType":"Text","ParameterInputType":"Textbox","ParameterMandatory":"Yes","ParameterLabel":"House Code","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"A simple unique code that you can remember.","ParameterInfo2":"The code appears on most screeens, so please choose a code that is self-descrptive and can be remembered easily.","ParameterInfo3":""},
   
     {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"4","ParameterName":"houseRegion","ParameterField":"houseRegion","ParameterDataType":"Text","ParameterInputType":"ListBox","ParameterMandatory":"Yes","ParameterLabel":"House Region","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"What region should your house be deployed","ParameterInfo2":"","ParameterInfo3":""},
    // {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"6","ParameterName":"Type","ParameterField":"resourceType","ParameterDataType":"Text","ParameterInputType":"Textbox","ParameterMandatory":"Yes","ParameterLabel":"Type","ParameterInput":"No","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"Provide the type","ParameterInfo2":"","ParameterInfo3":""},
    {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"6","ParameterName":"houseCidr","ParameterField":"resourceIpBlock","ParameterDataType":"Text","ParameterInputType":"Textbox","ParameterMandatory":"Yes","ParameterLabel":"House IP Block","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"Provide the house ip block","ParameterInfo2":"","ParameterInfo3":""},
    // {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"10","ParameterName":"EnableDnsHostnames","ParameterField":"resourcePublic","ParameterDataType":"Boolean","ParameterInputType":"Textbox","ParameterMandatory":"Yes","ParameterLabel":"House Public Resource?","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"Provide the house public resource?","ParameterInfo2":"","ParameterInfo3":""},
    // {"ParameterProvider":"aws","ParameterObject":"ServerHouse","ParameterSerial":"11","ParameterName":"EnableDnsSupport","ParameterField":"resourceDns","ParameterDataType":"Boolean","ParameterInputType":"Textbox","ParameterMandatory":"Yes","ParameterLabel":"DNS Support?","ParameterInput":"Yes","ParameterLength":"20","ParameterValidation":"","ParameterSource":"","ParameterInfo1":"Provide the dns support?","ParameterInfo2":"","ParameterInfo3":""}
]