export const imgLinks = {
    awsLogo:'/images/aws-white.webp',
    huawei: '/images/huawei.png',
    huaweiLight: '/images/huawei-light.png',
    awsdark: '/images/aws-dark.png',
    texture1: './images/texture1.png',
    nibss: '/images/nibss.png',
    rubies:'/images/rubies.png',
    image:'/images/image.png',
    gcp:'/images/gcp.webp',
    switch:'/images/switch.png',
    azure:'/images/azure.png',
    router:'/images/router.png',
    logo:'/images/qocent-logo.png',
    footerlogo:'images/qocent-footer.png',
    canva:'/images/canva.png',
    tier1:'/images/tier-1.jpg',
    tier2:'/images/tier-2.jpg',

    tier3:'/images/tier-3.jpg',

    aws:'images/aws.png',
}

export const huaweiIconLinks = {
    functionGraph :'/icons/huawei/functiongraph.png',
    rds :'/icons/huawei/rds.png',
    sfs :'/icons/huawei/sfs.png',
    user :'/icons/huawei/user.png',
    server :'/icons/huawei/server.png',
    nat :'/icons/huawei/nat.png',
    evs :'/icons/huawei/evs.png',
    elb :'/icons/huawei/elb.png',
    router :'/icons/huawei/router.png',
    waf:'icons/aws/waf.svg',

}

export const awsIconLinks = {
    functionGraph :'/icons/huawei/functiongraph.png',
    rds :'/icons/aws/rds.png',
    s3 :'/icons/aws/s3.png',
    user :'/icons/huawei/user.png',
    dynamodb:'icons/aws/dynamodb.png',
    waf:'icons/aws/waf.svg',
    server :'/icons/aws/server.png',
    nat :'/icons/huawei/nat.png',
    cloudSearch:'/icons/aws/cloud-search.svg',
    certificateManager:'/icons/aws/certificate-manager.svg',
    cloudWatch:'/icons/aws/cloud-watch.svg',
    cloudFront:'/icons/aws/cloud-front.svg',
    elb:'/icons/aws/elb.svg',
    cloudTrail:'/icons/aws/cloud-trail.svg',
    cloudWatchLogs:'/icons/aws/cloud-watch-logs.svg',
    cloudWatchMetrics:'/icons/aws/cloud-watch-metrics.svg',
    cloudWatchEvents:'/icons/aws/cloud-watch-events.svg',
    cloudWatchAlarms:'/icons/aws/cloud-watch-alarms.svg',
    ecr:'/icons/aws/ecr.svg',
    cm:'/icons/aws/certificate-manager.svg',
    ebs :'/icons/aws/ebs.png',
    lambda:'/icons/aws/lambda.svg',
    efs :'/icons/aws/efs.png',
    asg :'/icons/aws/asg.png',
    router :'/icons/huawei/router.png',
    
}

export const svgLinks = {
    cube: '/svg/cubes.svg',
    aws:'/svg/aws.svg',
    mosaic: '/svg/mosaic.svg',
    
    grunge:'/svg/grunge.svg',
    router:'/svg/router.svg',
    igw:'/svg/igw.svg',
    s3:'/svg/s3.svg',
    google:'/svg/google.svg',
    qocentLight:'/svg/qocent-light.svg',
    r53:'/svg/r53.svg',
    threed1:'/svg/3d1.svg',
    threed2:'/svg/3d2.svg',
    threed3:'/svg/3d3.svg',
    threed4:'/svg/3d4.svg',
    hero:'/svg/hero.svg',
    logo:'/svg/qocentlogo.svg',
    logoWhite:'/svg/qocentlogo2.svg',
    azure:'/svg/azure.svg',
}