import type { HouseData } from "./type";

export const houseData:HouseData[] = [
  {
    houseId: "1001",
    houseName: "Rubies Production Site",
    rooms: "2",
    alerts: 0,
    provider: "AWS",
    siteCode: "Rub-Prod-Site-1",
    houseCode: "Rub-Prod-Site-1",
    status: "Active",
    createdAt: "2025-01-09",
    ipRange:  "10.10.4.3",
  },
  {
    houseId: "1002",
    houseName: "Rubies Production Site",
    rooms: "1",
    alerts: 8,
    provider: "Huawei",
    status: "Active",
    siteCode: "Rub-Prod-Site-1",
    houseCode: "Rub-Prod-Site-2",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1003",
    houseName: "Qoovest",
    rooms: "2",
    alerts: 5,
    siteCode: "Qoov-Prod-Site-1",
    houseCode: "Qoov-Prod-Site-1",
    status: "Active",
    provider: "Huawei",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1004",
    houseName: "Qoonity",
    rooms: "1",
    provider: "Huawei",
    siteCode: "Qoon-Prod-Site-1",
    houseCode: "Qoon-Prod-Site-1",
    alerts: 9,
    status: "Active",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1005",
    provider: "AWS",
    siteCode: "NC-Prod-Site-1",
    houseCode: "NC-Prod-Site-1",
    houseName: "NCube",
    rooms: "3",
    alerts: 0,
    status: "Active",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1006",
    provider: "AWS",
    siteCode: "NC-Prod-Site-1",
    houseCode: "NC-Prod-Site-2",
    houseName: "NCube",
    rooms: "3",
    alerts: 2,
    status: "Active",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1007",
    provider: "AWS",
    siteCode: "NC-Prod-Site-1",
    houseCode: "NC-Prod-Site-3",
    houseName: "NCube",
    rooms: "3",
    alerts: 0,
    status: "Active",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1008",
    houseName: "Tymer",
    provider: "AWS",
    siteCode: "Tymer-Prod-Site-1",
    houseCode: "Tymer-Prod-Site-1",
    rooms: "4",
    alerts: 6,
    status: "Suspended",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1008",
    houseName: "Tymer",
    provider: "AWS",
    siteCode: "Tymer-Prod-Site-1",
    houseCode: "Tymer-Prod-Site-2",
    rooms: "4",
    alerts: 6,
    status: "Suspended",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1009",
    houseName: "Qoovest",
    rooms: "2",
    alerts: 5,
    siteCode: "Qoov-Prod-Site-1",
    houseCode: "Qoov-Prod-Site-2",
    status: "Active",
    provider: "Huawei",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },

];
