import type { HouseData } from "./type";

export const houseData:HouseData[] = [
  {
    houseId: "1001",
    houseName: "Rubies Production Site",
    rooms: "2",
    alerts: 0,
    provider: "AWS",
    region: "US (California)",
    siteCode: "RUB-PROD-SITE-1",
    houseCode: "RUB-PROD-SITE-1",
    status: "Active",
    createdAt: "2025-01-09",
    ipRange:  "10.10.4.3",
  },
  {
    houseId: "1002",
    houseName: "Rubies Production Site",
    rooms: "1",
    alerts: 8,
    provider: "Huawei",
    region: "US (Virginia)",
    status: "Active",
    siteCode: "RUB-PROD-SITE-1",
    houseCode: "RUB-PROD-SITE-1",
    createdAt: "2025-01-09",

    ipRange: "10.10.4.3",
  },
  {
    houseId: "1003",
    houseName: "Qoovest",
    rooms: "2",
    alerts: 5,
    siteCode: "RUB-PROD-SITE-1",
    houseCode: "RUB-PROD-SITE-1",
    region: "UK",
    status: "Active",
    provider: "Huawei",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1004",
    houseName: "Qoonity",
    rooms: "1",
    provider: "Huawei",
    siteCode: "RUB-PROD-SITE-1",
    houseCode: "RUB-PROD-SITE-1",
    alerts: 9,
    region: "France",
    status: "Active",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1005",
    provider: "AWS",
    siteCode: "RUB-PROD-SITE-1",
    houseCode: "RUB-PROD-SITE-1",
    houseName: "NCube",
    rooms: "3",
    alerts: 15,
    region: "Germany",
    status: "Active",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
  {
    houseId: "1006",
    houseName: "Tymer",
    provider: "AWS",
    siteCode: "RUB-PROD-SITE-1",
    houseCode: "RUB-PROD-SITE-1",
    rooms: "4",
    alerts: 6,
    region: "South Africa",
    status: "Suspended",
    createdAt: "2025-01-09",
    ipRange: "10.10.4.3",
  },
];
