import type { SiteData } from "./type";

export const siteData: SiteData[] = [
  {
    id: "1",
    resource: "MySQL-Prod-01",
    parentCode: "1001",
    cateogry: "Database",
    alerts: 2,
    parent: "Rubies Production Site",
    code: "DB-01",
    status: "Active",
    type: "Database",
  },
  {
    id: "11",
    resource: "MySQL-Prod-01",
    cateogry: "Database",
    parentCode: "1001",
    alerts: 2,
    parent: "Rubies Production Site",
    code: "DB-01",
    status: "Active",
    type: "Database",
  },

  {
    id: "19",
    resource: "Main Web Server",
    cateogry: "Server",
    alerts: 5,
    parentCode: "1001",
    parent: "Tymer",
    code: "SRV-01",
    status: "Active",
    type: "Server",
  },
  {
    id: "18",
    resource: "Auth Service",
    cateogry: "API",
    alerts: 1,
    parentCode: "1001",
    parent: "NCube",
    code: "SRV-02",
    status: "Active",
    type: "Server",
  },
  {
    id: "1010",
    resource: "Mongo-Staging",
    cateogry: "Database",
    alerts: 3,
    parent: "Qoonity",
    code: "DB-ST-01",
    parentCode: "1002",
    status: "Suspended",
    type: "Database",
  },
  {
    id: "17",
    resource: "Worker Node 1",
    cateogry: "Compute",
    alerts: 0,
    parent: "Qoovest",
    code: "SRV-W-01",
    status: "Active",
    parentCode: "1004",
    type: "Server",
  },
  {
    id: "12",
    resource: "Postgres-Analytics",
    cateogry: "Database",
    alerts: 0,
    parent: "Qoovest",
    code: "DB-AN-02",
    status: "Inactive",
    parentCode: "1002",
    type: "Database",
  },
  {
    id: "13",
    resource: "Main Web Server",
    cateogry: "Server",
    alerts: 5,
    parentCode: "1001",
    parent: "Tymer",
    code: "SRV-01",
    status: "Active",
    type: "Server",
  },
  {
    id: "14",
    resource: "Auth Service",
    cateogry: "API",
    alerts: 1,
    parentCode: "1003",
    parent: "NCube",
    code: "SRV-02",
    status: "Active",
    type: "Server",
  },
  {
    id: "15",
    resource: "Mongo-Staging",
    cateogry: "Database",
    alerts: 3,
    parent: "Qoonity",
    code: "DB-ST-01",
    parentCode: "1004",
    status: "Suspended",
    type: "Database",
  },
  {
    id: "16",
    resource: "Worker Node 1",
    cateogry: "Compute",
    parentCode: "1005",
    alerts: 0,
    parent: "Qoovest",
    code: "SRV-W-01",
    status: "Active",
    type: "Server",
  },
];
