import type { SiteData } from "./type";

export const siteData: SiteData[] = [
  {
    id: "100001",
    resource: "MySQL-Prod-01",
    parentCode: "100001",
    category: "Database",
    alerts: 2,
    parent: "Rubies Production Site",
    code: "DB-01",
    status: "Active",
    type: "Database",
    resourceType: "Database",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100002",
    resource: "MySQL-Prod-01",
    category: "Database",
    parentCode: "100001",
    alerts: 2,
    parent: "Rubies Production Site",
    code: "DB-01",
    status: "Active",
    type: "S3",
    resourceType: "S3",
    createdAt: "2025-01-01",
    bill: 100,
  },

  {
    id: "100003",
    resource: "Main Web Server",
    category: "Server",
    alerts: 5,
    parentCode: "100001",
    parent: "Tymer",
    code: "SRV-01",
    status: "Active",
    type: "Server",
    resourceType: "Server",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100004",
    resource: "Auth Service",
    category: "API",
    alerts: 1,
    parentCode: "100001",
    parent: "NCube",
    code: "SRV-02",
    status: "Active",
    type: "Proxy",
    resourceType: "Proxy",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100005",
    resource: "Mongo-Staging",
    category: "Database",
    alerts: 3,
    parent: "Qoonity",
    code: "DB-ST-01",
    parentCode: "100002",
    status: "Suspended",
    type: "Proxy",
    resourceType: "Proxy",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100006",
    resource: "Worker Node 1",
    category: "Compute",
    alerts: 0,
    parent: "Qoovest",
    code: "SRV-W-01",
    status: "Active",
    parentCode: "100004",
    type: "Server",
    resourceType: "Server",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100007",
    resource: "Postgres-Analytics",
    category: "Database",
    alerts: 0,
    parent: "Qoovest",
    code: "DB-AN-02",
    status: "Suspended",
    parentCode: "100002",
    type: "Database",
    resourceType: "Database",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100008",
    resource: "Main Web Server",
    category: "Server",
    alerts: 5,
    parentCode: "100001",
    parent: "Tymer",
    code: "SRV-01",
    status: "Active",
    type: "Server",
    resourceType: "Server",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100009",
    resource: "Auth Service",
    category: "API",
    alerts: 1,
    parentCode: "100003",
    parent: "NCube",
    code: "SRV-02",
    status: "Active",
    type: "Server",
    resourceType: "Server",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100010",
    resource: "Mongo-Staging",
    category: "Database",
    alerts: 3,
    parent: "Qoonity",
    code: "DB-ST-01",
    parentCode: "100004",
    status: "Suspended",
    type: "Database",
    resourceType: "Database",
    createdAt: "2025-01-01",
    bill: 100,
  },
  {
    id: "100011",
    resource: "Worker Node 1",
    category: "Compute",
    parentCode: "100005",
    alerts: 0,
    parent: "Qoovest",
    code: "SRV-W-01",
    status: "Active",
    type: "Server",
    resourceType: "Server",
    createdAt: "2025-01-01",
    bill: 100,
  },
];
